{host, ...}: let
  inherit
    (import ../../../hosts/${host}/variables.nix)
    browser
    terminal
    ;
in {
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$modifier,Return,exec,terminal-same-dir"
      "$modifier,K,exec,list-keybinds"
      "$modifier SHIFT,Return,exec,rofi-launcher"
      "$modifier SHIFT,W,exec,web-search"
      "$modifier ALT,W,exec,wallsetter"
      "$modifier SHIFT,N,exec,swaync-client -rs"
      "$modifier,W,exec,${browser}"
      "$modifier,Y,exec,kitty -e yazi"
      "$modifier,E,exec,thunar"
      "$modifier,S,exec,screenshootin"
      "$modifier SHIFT,S,exec,claude-image-helper region"
      "$modifier ALT,S,exec,claude-image-helper capture"
      "$modifier CONTROL,S,exec,claude-image-helper window"
      "$modifier,D,exec,droidcam"
      "$modifier,O,exec,obs"
      "$modifier,C,exec,hyprpicker -a"
      "$modifier,G,fullscreen,"
      "$modifier,T,exec,pypr toggle term"
      "$modifier,M,exec,pavucontrol"
      "$modifier,Q,killactive,"
      "$modifier,P,pseudo,"
      "$modifier,V,exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy"
      "$modifier SHIFT,I,togglesplit,"
      "$modifier,F,exec,wl-kbptr -o modes=floating,click -o mode_floating.source=detect"
      "$modifier SHIFT,F,togglefloating,"
      "$modifier ALT,F,workspaceopt, allfloat"
      "$modifier SHIFT,C,exit,"
      "$modifier SHIFT,left,movewindow,l"
      "$modifier SHIFT,right,movewindow,r"
      "$modifier SHIFT,up,movewindow,u"
      "$modifier SHIFT,down,movewindow,d"
      "$modifier SHIFT,h,movewindow,l"
      "$modifier SHIFT,l,movewindow,r"
      "$modifier SHIFT,k,movewindow,u"
      "$modifier SHIFT,j,movewindow,d"
      "$modifier ALT, left, swapwindow,l"
      "$modifier ALT, right, swapwindow,r"
      "$modifier ALT, up, swapwindow,u"
      "$modifier ALT, down, swapwindow,d"
      "$modifier ALT, 43, swapwindow,l"
      "$modifier ALT, 46, swapwindow,r"
      "$modifier ALT, 45, swapwindow,u"
      "$modifier ALT, 44, swapwindow,d"
      "$modifier,left,movefocus,l"
      "$modifier,right,movefocus,r"
      "$modifier,up,movefocus,u"
      "$modifier,down,movefocus,d"
      "$modifier,h,movefocus,l"
      "$modifier,l,movefocus,r"
      "$modifier,k,movefocus,u"
      "$modifier,j,movefocus,d"
      "ALT,1,workspace,1"
      "ALT,2,workspace,2"
      "ALT,3,workspace,3"
      "ALT,4,workspace,4"
      "ALT,5,workspace,5"
      "ALT,6,workspace,6"
      "ALT,7,workspace,7"
      "ALT,8,workspace,8"
      "ALT,9,workspace,9"
      "ALT,0,workspace,10"
      "ALT SHIFT,SPACE,movetoworkspace,special"
      "ALT,SPACE,togglespecialworkspace"
      "ALT SHIFT,1,movetoworkspace,1"
      "ALT SHIFT,2,movetoworkspace,2"
      "ALT SHIFT,3,movetoworkspace,3"
      "ALT SHIFT,4,movetoworkspace,4"
      "ALT SHIFT,5,movetoworkspace,5"
      "ALT SHIFT,6,movetoworkspace,6"
      "ALT SHIFT,7,movetoworkspace,7"
      "ALT SHIFT,8,movetoworkspace,8"
      "ALT SHIFT,9,movetoworkspace,9"
      "ALT SHIFT,0,movetoworkspace,10"
      "$modifier CONTROL,right,workspace,e+1"
      "$modifier CONTROL,left,workspace,e-1"
      "$modifier,mouse_down,workspace, e+1"
      "$modifier,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "$modifier, mouse:272, movewindow"
      "$modifier, mouse:273, resizewindow"
    ];
  };
}
