{inputs, ...}: {
  imports = [
    ./boot.nix
    ./claude-openai-wrapper.nix
    ./flatpak.nix
    ./fonts.nix
    ./greetd.nix
    ./hardware.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./nixified-ai.nix
    ./ollama.nix
    ./packages.nix
    ./printing.nix
    ./security.nix
    ./services.nix
    ./ssh-secrets.nix
    ./starfish.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    inputs.stylix.nixosModules.stylix
  ];
}
